# Generated by Django 3.2.10 on 2021-12-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JiraToken',
        ),
    ]
