# Generated by Django 3.2.10 on 2021-12-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='writer',
            new_name='writers',
        ),
    ]
